import { useRef, useState } from 'react';
import { Canvas, useFrame } from '@react-three/fiber';
import {
  SoftShadows,
  Float,
  Sky,
  OrbitControls,
  PerformanceMonitor,
  useGLTF
} from '@react-three/drei';
import { easing } from 'maath';
import { cdn, DecoderPath } from '@/constants';

function rectanglePath(t, T = 2, x1 = 0.8, y1 = 0.8, x2 = -0.8, y2 = -0.8) {
  // 确保 x1, y1 是左上角，x2, y2 是右下角
  let left = Math.min(x1, x2);
  let right = Math.max(x1, x2);
  let top = Math.max(y1, y2);
  let bottom = Math.min(y1, y2);

  // 计算矩形边长
  let width = right - left;
  let height = top - bottom;
  let perimeter = 2 * (width + height);

  // 计算匀速移动的距离
  let speed = perimeter / T; // 每秒移动的长度
  let d = (t % T) * speed; // 当前时间下的移动距离（归一化到 [0, perimeter]）

  // 计算当前在哪条边上
  if (d < width) {
    return [left + d, top]; // 上边 (左 -> 右)
  } else if (d < width + height) {
    return [right, top - (d - width)]; // 右边 (上 -> 下)
  } else if (d < 2 * width + height) {
    return [right - (d - width - height), bottom]; // 下边 (右 -> 左)
  } else {
    return [left, bottom + (d - 2 * width - height)]; // 左边 (下 -> 上)
  }
}

function Light() {
  const ref = useRef();
  useFrame((state, delta) => {
    const pointer = rectanglePath(state.clock.getElapsedTime(), 10);
    easing.dampE(
      ref.current.rotation,
      [(pointer[1] * Math.PI) / 50, (pointer[0] * Math.PI) / 20, 0],
      0.2,
      delta
    );
  });
  return (
    <group ref={ref}>
      <directionalLight
        position={[5, 5, -8]}
        castShadow
        intensity={5}
        shadow-mapSize={2048}
        shadow-bias={-0.001}
      >
        <orthographicCamera attach="shadow-camera" args={[-8.5, 8.5, 8.5, -8.5, 0.1, 20]} />
      </directionalLight>
    </group>
  );
}

export function RoomWithSoftShadowsApp({ eventSource }) {
  const [bad, set] = useState(false);
  const [{ enabled, samples, ...config }] = useState({
    enabled: true,
    size: 35,
    focus: 0.5,
    samples: 16
  });
  return (
    <Canvas
      shadows
      eventSource={eventSource}
      dpr={[1, THREEGlobals.devicePixelRatio]}
      camera={{ position: [5, 2, 10], fov: 50 }}
    >
      <PerformanceMonitor onDecline={() => set(true)} />
      {enabled && <SoftShadows {...config} samples={bad ? Math.min(6, samples) : samples} />}
      <OrbitControls makeDefault />
      <color attach="background" args={['#d0d0d0']} />
      <fog attach="fog" args={['#d0d0d0', 8, 35]} />
      <ambientLight intensity={0.4} />
      <Light />
      <Room scale={0.5} position={[0, -1, 0]} />
      <Sphere />
      <Sphere position={[2, 4, -8]} scale={0.9} />
      <Sphere position={[-2, 2, -8]} scale={0.8} />
      <Sky inclination={0.52} scale={20} />
    </Canvas>
  );
}

function Sphere({ color = 'hotpink', floatIntensity = 15, position = [0, 5, -8], scale = 1 }) {
  return (
    <Float floatIntensity={floatIntensity}>
      <mesh castShadow position={position} scale={scale}>
        <sphereGeometry />
        <meshBasicMaterial color={color} roughness={1} />
      </mesh>
    </Float>
  );
}

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 room.glb --transform
Author: Anex (https://sketchfab.com/anex)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/room-6417cbc1870a4a1691cca06912ae0369
Title: Room
*/
export function Room(props) {
  const { nodes, materials } = useGLTF(
    `${cdn.R3F_ASSETS}room-transformed_png-texture.glb`,
    DecoderPath.GLTF
  );
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.krzeslo_1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.krzeslo_okno}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials.krzeslo_prawe}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials.krzeslo_srodek}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials.podloga}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11.geometry}
          material={materials.sciana_okno}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_12.geometry}
          material={materials['stolik.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16.geometry}
          material={materials['Material.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials['Material.004']}
        />
        <mesh geometry={nodes.Object_13.geometry}>
          <meshStandardMaterial transparent opacity={0.5} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_14.geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_15.geometry}
          material={materials['Material.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_17.geometry}
          material={materials.mata}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_18.geometry}
          material={materials.stolik}
        />
      </group>
    </group>
  );
}
