/**
 * 参考自 https://codesandbox.io/p/sandbox/6d97z4
 * 如遇资源失效， 可自行前往下载
 * */
import { easing } from "maath";
import { Canvas, useFrame, useThree } from "@react-three/fiber"
import { Sky, Bvh } from "@react-three/drei"
import { EffectComposer, Selection, Select, Outline, N8AO, TiltShift2, ToneMapping } from "@react-three/postprocessing"
import { useState, useCallback, useEffect } from "react"
import { debounce } from "lodash-es";
import {
  useGLTF, useEnvironment,
  Text,
  Mask, useMask
} from "@react-three/drei"
import { useRef } from "react"
import { CDN_PREFIX } from "@/constants";

const FONT_URL = `${CDN_PREFIX}/inter_regular.woff`;

export const ShoppingApp = ({ eventSource }) => {
  return (
    <Canvas eventSource={eventSource} flat dpr={THREEGlobals.devicePixelRatio} gl={{ antialias: false }}
            camera={{ position: [0, 1, 6], fov: 25, near: 1, far: 20 }}>
      <ambientLight intensity={1.5 * Math.PI}/>
      <Sky/>
      <Bvh firstHitOnly>
        <Selection>
          <Effects/>
          <Scene rotation={[0, Math.PI / 2, 0]} position={[0, -1, -0.85]}/>
        </Selection>
      </Bvh>
    </Canvas>
  )
}

function Effects() {
  const { size } = useThree()
  useFrame((state, delta) => {
    easing.damp3(state.camera.position, [state.pointer.x, 1 + state.pointer.y / 2, 8 + Math.atan(state.pointer.x * 2)], 0.3, delta)
    state.camera.lookAt(state.camera.position.x * 0.9, 0, -4)
  })
  return (
    <EffectComposer stencilBuffer disableNormalPass autoClear={false} multisampling={4}>
      {/*<N8AO halfRes aoSamples={5} aoRadius={0.4} distanceFalloff={0.75} intensity={1}/>*/}
      <Outline visibleEdgeColor="white" hiddenEdgeColor="white" blur width={size.width * 1.25} edgeStrength={10}/>
      {/*<TiltShift2 samples={5} blur={0.1}/>*/}
      <ToneMapping/>
    </EffectComposer>
  )
}


/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 kitchen.glb --transform
Files: kitchen.glb [134.46MB] > kitchen-transformed.glb [2.1MB] (98%)
*/
function Scene(props) {
  // Load model

  const { nodes, materials } = useGLTF(
    `${CDN_PREFIX}/kitchen-transformed_png-texture.glb`,
    "draco/gltf/",
  )
  // Load environment (using it only on the chairs, for reflections)
  const env = useEnvironment({ files: `${CDN_PREFIX}/potsdamer_platz_1k.hdr` })
  // Hover state
  const [hovered, hover] = useState(null)
  // Debounce hover a bit to stop the ticker from being erratic
  const debouncedHover = useCallback(debounce(hover, 30), [])
  const over = (name) => {
    return (e) => {
      e.stopPropagation();
      debouncedHover(name)
    }
  }
  // Get the priced item
  const price = { KNOXHULT: 5999, BRÖNDEN: 433, SKAFTET: 77, FANBYN: 255, VOXLÖV: 1699, LIVSVERK: 44 }[hovered] ?? 5999


  const set = useThree(state => state.set)
  useEffect(() => {
    set({
      onPointerMissed: (pointer) => {
        debouncedHover(null)
      }
    })
  }, [])
  return (
    <>
      <group {...props}>
        <mesh geometry={nodes.vase1.geometry} material={materials.gray} material-envMap={env}/>
        <mesh geometry={nodes.bottle.geometry} material={materials.gray} material-envMap={env}/>
        <mesh geometry={nodes.walls_1.geometry} material={materials.floor}/>
        <mesh geometry={nodes.walls_2.geometry} material={materials.walls}/>
        <mesh geometry={nodes.plant_1.geometry} material={materials.potted_plant_01_leaves}/>
        <mesh geometry={nodes.plant_2.geometry} material={materials.potted_plant_01_pot}/>
        <mesh geometry={nodes.cuttingboard.geometry} material={materials.walls}/>
        <mesh geometry={nodes.bowl.geometry} material={materials.walls}/>
        <Select enabled={hovered === "BRÖNDEN"} onPointerOver={over("BRÖNDEN")} onClick={over("BRÖNDEN")} onPointerOut={() => debouncedHover(null)}>
          <mesh geometry={nodes.carpet.geometry} material={materials.carpet}/>
        </Select>
        <Select enabled={hovered === "VOXLÖV"} onPointerOver={over("VOXLÖV")} onClick={over("VOXLÖV")} onPointerOut={() => debouncedHover(null)}>
          <mesh geometry={nodes.table.geometry} material={materials.walls} material-envMap={env} material-envMapIntensity={0.5}/>
        </Select>
        <Select enabled={hovered === "FANBYN"} onPointerOver={over("FANBYN")} onClick={over("FANBYN")} onPointerOut={() => debouncedHover(null)}>
          <mesh geometry={nodes.chairs_1.geometry} material={materials.walls}/>
          <mesh geometry={nodes.chairs_2.geometry} material={materials.plastic} material-color="#1a1a1a" material-envMap={env}/>
        </Select>
        <Select enabled={hovered === "LIVSVERK"} onPointerOver={over("LIVSVERK")} onClick={over("LIVSVERK")}
                onPointerOut={() => debouncedHover(null)}>
          <mesh geometry={nodes.vase.geometry} material={materials.gray} material-envMap={env}/>
        </Select>
        <Select enabled={hovered === "SKAFTET"} onPointerOver={over("SKAFTET")} onClick={over("SKAFTET")} onPointerOut={() => debouncedHover(null)}>
          <mesh geometry={nodes.lamp_socket.geometry} material={materials.gray} material-envMap={env}/>
          <mesh geometry={nodes.lamp.geometry} material={materials.gray}/>
          <mesh geometry={nodes.lamp_cord.geometry} material={materials.gray} material-envMap={env}/>
        </Select>
        <mesh geometry={nodes.kitchen.geometry} material={materials.walls}/>
        <mesh geometry={nodes.sink.geometry} material={materials.chrome} material-envMap={env}/>
      </group>
      <Text position={[1, 1.25, 0]} color="black" fontSize={0.15} font={FONT_URL} letterSpacing={-0.05}>
        {hovered ? hovered : "KNOXHULT"}
      </Text>
      {/** Forward the price to the ticker component */}
      <Price value={price} position={[-2, 0.3, -3.25]}/>
    </>
  )
}

const Price = ({ value, currency = "$", ...props }) => (
  <group {...props}>
    {[...`✨✨✨${value}`.slice(-4)].map((num, index) => (
      <Counter index={index} value={num === "✨" ? -1 : num} key={index} speed={0.1 * (4 - index)}/>
    ))}
    <Text children={currency} anchorY="bottom" position={[4 * 1.1, -0.25, 0]} fontSize={1} font={FONT_URL}/>
    <Mask id={1}>
      <planeGeometry args={[10, 1.55]}/>
    </Mask>
  </group>
)

function Counter({ index, value, speed = 0.1 }) {
  const ref = useRef()
  const stencil = useMask(1)
  useFrame((state, delta) => easing.damp(ref.current.position, "y", value * -2, speed, delta))
  return (
    <group position-x={index * 1.1} ref={ref}>
      {[0, 1, 2, 3, 4, 5, 6, 7, 8, 9].map((number) => (
        <Text key={number} position={[0, number * 2, 0]} fontSize={2} font={FONT_URL}>
          {number}
          <meshBasicMaterial {...stencil} />
        </Text>
      ))}
    </group>
  )
}
